// <auto-generated />
using System;
using IARA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IARA.Data.Migrations
{
    [DbContext(typeof(IaraContext))]
    [Migration("20230116033842_TesteMigration")]
    partial class TesteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IARA.Domain.Entities.CotacaoEntitie", b =>
                {
                    b.Property<int>("IdCotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CnpjCliente")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("DataCotacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEntregaCotacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("NumeroCotacao")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdCotacao");

                    b.ToTable("Cotacao");
                });

            modelBuilder.Entity("IARA.Domain.Entities.ItemCotacaoEntitie", b =>
                {
                    b.Property<long>("ItemCotacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("NumeroItem")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(19,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cotacaoIdCotacao")
                        .HasColumnType("int");

                    b.HasKey("ItemCotacaoId");

                    b.HasIndex("cotacaoIdCotacao");

                    b.ToTable("CotacaoItem");
                });

            modelBuilder.Entity("IARA.Domain.Entities.ItemCotacaoEntitie", b =>
                {
                    b.HasOne("IARA.Domain.Entities.CotacaoEntitie", "cotacao")
                        .WithMany("CotacaoItem")
                        .HasForeignKey("cotacaoIdCotacao");

                    b.Navigation("cotacao");
                });

            modelBuilder.Entity("IARA.Domain.Entities.CotacaoEntitie", b =>
                {
                    b.Navigation("CotacaoItem");
                });
#pragma warning restore 612, 618
        }
    }
}
